Repository chronhq/backend, pull requests merged in 2019-01, with the labels that each got.

#22 Initial implementation of narrative models
  config/requirements.txt
  project/api/migrations/0005_auto_20181230_1155.py
  project/api/models.py
  project/api/tests.py
  project/chron/settings.py
Labels: A0-pleasereview, M2-narratives

#32 Remove uniqueness constraint on CachedData
  project/api/migrations/0005_auto_20181230_1918.py
  project/api/models.py
Labels: A0-pleasereview, F2-bug, M1-factoids

#31 Implement ranking algorithm
  config/requirements.txt
  project/api/models.py
Labels: A8-looksgood, M0-interactivemap, M1-factoids

#37 City table
  project/api/factories.py
  project/api/migrations/0007_city.py
  project/api/models.py
  project/api/serializers.py
  project/api/tests.py
  project/api/urls.py
  project/api/views.py
Labels: A8-looksgood, M0-interactivemap

#39 Remove control types
  project/api/models.py
Labels: A8-looksgood, M0-interactivemap
