Repository chronhq/backend, pull requests merged in 2019-02, with the labels that each got.

#44 Reverse m2m with AP in STV serializer
  .gitignore
  project/api/migrations/0008_auto_20190129_1408.py
  project/api/models.py
  project/api/serializers.py
Labels: A8-looksgood, M0-interactivemap, M5-autonomylevel

#42 Mixed model changes
  project/api/migrations/0008_auto_20190126_2329.py
  project/api/migrations/0009_auto_20190126_2347.py
  project/api/migrations/0010_auto_20190127_1848.py
  project/api/migrations/0011_auto_20190127_2143.py
  project/api/migrations/0012_merge_20190206_1106.py
  project/api/models.py
  project/api/tests.py
  project/api/views.py
Labels: A0-pleasereview, A8-looksgood

#35 MVT endpoint to render CachedData
  project/api/migrations/0007_tilebbox.py
  project/api/migrations/0008_merge_20190120_1751.py
  project/api/migrations/0009_merge_20190207_0037.py
  project/api/sql/TileBBox.sql
  project/api/urls.py
  project/api/views.py
Labels: A8-looksgood, M0-interactivemap, M1-factoids

#53 Merge migrations
  project/api/migrations/0013_merge_20190208_0424.py
Labels: A0-pleasereview

#56 API Changes
  project/api/serializers.py
  project/api/views.py
Labels: A8-looksgood, M2-narratives

#57 Add URL field to Narrative
  project/api/migrations/0014_auto_20190209_2226.py
  project/api/models.py
  project/api/tests.py
Labels: A0-pleasereview, M2-narratives

#50 Nest narration attached_events
  project/api/admin.py
  project/api/serializers.py
  project/api/tests.py
Labels: A8-looksgood, M2-narratives

#55 Remove CD.location null constraint and extend filtering
  project/api/migrations/0014_auto_20190209_0147.py
  project/api/models.py
  project/api/views.py
Labels: A0-pleasereview, M1-factoids

#58 Merge migrations
  project/api/migrations/0015_merge_20190209_2303.py
Labels: A0-pleasereview

#52 City and Narration MVT endpoints
  project/api/migrations/0013_merge_20190208_0428.py
  project/api/migrations/0014_merge_20190209_2217.py
  project/api/migrations/0016_merge_20190210_1618.py
  project/api/urls.py
  project/api/views.py
Labels: A8-looksgood, M0-interactivemap, M2-narratives

#45 Added visual_center field for labeling maps.
  config/requirements.txt
  project/api/migrations/0008_auto_20190208_1552.py
  project/api/migrations/0014_merge_20190208_1700.py
  project/api/migrations/0015_auto_20190208_1810.py
  project/api/models.py
  project/api/tests.py
Labels: A8-looksgood

#76 Wikidata_id and event_type unique together constraint
  project/api/migrations/0004_auto_20190220_0536.py
  project/api/models.py
Labels: A0-pleasereview, M1-factoids

#82 Add STV T aggregation
  project/api/views.py
Labels: A0-pleasereview

#83 Fix README for production changes
  README.md
Labels: A0-pleasereview, F5-documentation
