Repository chronhq/backend, pull requests merged in 2020-04, with the labels that each got.

#226 Celery
  config/requirements.txt
  docker-compose.override.yml
  docker-compose.prod.yml
  docker-compose.yml
  project/api/helpers/__init__.py
  project/api/helpers/geometry.py
  project/api/helpers/overlaps.py
  project/api/management/commands/clean_stvs.py
  project/api/tasks/__init__.py
  project/api/tasks/add_new_stv.py
  project/api/tests/stv_tests.py
  project/api/urls.py
  project/api/views/endpoints/__init__.py
  project/api/views/endpoints/stv_tasks.py
  project/api/views/stv_view.py
  project/celery.sh
  project/chron/__init__.py
  project/chron/tasks_queue.py
Labels: A8-looksgood, F6-refactor, F7-optimisation

#231 Pull frontend images from docker hub
  Makefile
  project/celery.sh
Labels: A0-pleasereview, F8-enhancement

#232 Schedule updating Cached Data
  project/.pylintrc
  project/celery.sh
  project/chron/tasks_queue.py
Labels: A0-pleasereview, F7-optimisation
